'use client';
import { useCallback,useEffect,useRef,useState } from 'react';
import { Button } from '@/components/ui/button';
import { Skeleton } from '@/components/ui/skeleton';
import { fetchExchanges } from '@/lib/exchanges-transport';
import { formatExchangeDate } from '@/lib/exchange-date';
import { EXCHANGE_CHANNEL_LABELS,type ExchangesPage } from '@/lib/validations/exchanges';
export function ExchangeHistory({contactId,companyId,onNavigate}:{contactId?:string;companyId?:string;onNavigate?:(href:string)=>void}) {
 const [result,setResult]=useState<ExchangesPage|null>(null),[page,setPage]=useState(1),[loading,setLoading]=useState(false);const epoch=useRef(0),permitted=useRef(true);
 const refresh=useCallback(async()=>{if(!permitted.current)return;const stamp=++epoch.current;setLoading(true);const data=await fetchExchanges(contactId?{contact_id:contactId}:{company_id:companyId!},page);if(stamp!==epoch.current||!permitted.current)return;if(data.status==='unauthenticated'||data.status==='forbidden'){setResult(null);window.dispatchEvent(new Event('crm-session-denied'));return;}if(data.status==='success'&&page>Math.max(1,Math.ceil(data.total/25))){setPage(Math.max(1,Math.ceil(data.total/25)));return;}setResult(data);setLoading(false);},[contactId,companyId,page]);
 useEffect(()=>{permitted.current=true;const run=()=>refresh().catch(()=>setLoading(false));run();const expire=()=>{permitted.current=false;epoch.current++;setResult(null);};for(const e of ['focus','online','crm-data-changed','crm-session-ready'])window.addEventListener(e,run);window.addEventListener('crm-session-expired',expire);return()=>{epoch.current++;for(const e of ['focus','online','crm-data-changed','crm-session-ready'])window.removeEventListener(e,run);window.removeEventListener('crm-session-expired',expire);};},[refresh]);
 return <section aria-label="Historique des échanges" aria-busy={loading} className="space-y-3 border-t pt-5"><h2 className="text-sm font-medium">Échanges{result?.status==='success'?` (${result.total})`:''}</h2>{!result?<Skeleton className="h-24 w-full"/>:result.status!=='success'?<><p role="alert">{result.message}</p><Button type="button" variant="outline" onClick={()=>refresh().catch(()=>setLoading(false))}>Réessayer l’historique</Button></>:<><p className="text-xs text-muted-foreground">Dernière interaction : {result.last_interaction?formatExchangeDate(result.last_interaction.occurred_at):'Aucune'}</p>{result.total===0?<p className="text-sm text-muted-foreground">Aucun échange enregistré.</p>:<ol className="space-y-4">{result.exchanges.map(exchange=><li key={exchange.id} data-exchange-id={exchange.id} className="space-y-1 border-b pb-3"><p className="text-sm font-medium">{EXCHANGE_CHANNEL_LABELS[exchange.channel]} · {formatExchangeDate(exchange.occurred_at)}</p><p className="text-xs text-muted-foreground">{exchange.company_id?<a className="inline-flex min-h-11 max-w-full items-center whitespace-normal [overflow-wrap:anywhere] underline" href={`/societes?panel=${exchange.company_id}`} onClick={event=>{if(onNavigate&&!event.metaKey&&!event.ctrlKey&&!event.shiftKey&&!event.altKey){event.preventDefault();onNavigate(`/societes?panel=${exchange.company_id}`);}}}>{exchange.company_name?.trim() || 'Société historique · nom indisponible'}</a>:'Sans société historique'}{companyId?<a className="ml-3 inline-flex min-h-11 max-w-full items-center whitespace-normal [overflow-wrap:anywhere] underline" href={`/contacts?panel=${exchange.contact_id}`} onClick={event=>{if(onNavigate&&!event.metaKey&&!event.ctrlKey&&!event.shiftKey&&!event.altKey){event.preventDefault();onNavigate(`/contacts?panel=${exchange.contact_id}`);}}}>{exchange.contact_name?.trim() || 'Contact · nom indisponible'}</a>:null}</p>{exchange.notes?<p className="whitespace-pre-wrap text-sm [overflow-wrap:anywhere]">{exchange.notes}</p>:<p className="text-xs text-muted-foreground">Sans note.</p>}</li>)}</ol>}{result.total>25?<div className="flex flex-wrap items-center gap-2"><Button type="button" variant="outline" disabled={loading||page===1} onClick={()=>setPage(p=>p-1)}>Échanges précédents</Button><span className="text-xs">{page} / {Math.ceil(result.total/25)}</span><Button type="button" variant="outline" disabled={loading||page*25>=result.total} onClick={()=>setPage(p=>p+1)}>Échanges suivants</Button></div>:null}</>}</section>;
}
