'use client';
import { useEffect,useRef,useState } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Skeleton } from '@/components/ui/skeleton';
import { Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription,DialogFooter } from '@/components/ui/dialog';
import { fetchCompanies,fetchCompany } from '@/lib/companies-transport';
import { contactCompanyReadSchema,type CompaniesPage } from '@/lib/validations/companies';
import { exchangeFieldsSchema,EXCHANGE_CHANNEL_LABELS } from '@/lib/validations/exchanges';
import { parisCandidates,resolveParisDate } from '@/lib/exchange-date';
import { sendExchangeCommand } from '@/lib/exchanges-transport';
import { acknowledgeExchange,exchangeDirty,freshExchangeDraft,readExchangeDraft,removeExchangeDraft,writeExchangeDraft,type ExchangeDraft } from '@/lib/exchanges-drafts';
export type ExchangeEditorHandle={dirty:()=>boolean;busy:()=>boolean;focusInvalid:()=>boolean;hasPending:()=>boolean;save:()=>Promise<boolean>;discard:()=>boolean|void};
export function ExchangeEditor({ownerId,contactId,handle,onBusyChange}:{ownerId:string;contactId:string;handle:React.RefObject<ExchangeEditorHandle|null>;onBusyChange:(busy:boolean)=>void}){
 const [draft,setDraft]=useState<ExchangeDraft|null>(null),ref=useRef<ExchangeDraft|null>(null),active=useRef(true),flight=useRef(false);
 const [open,setOpen]=useState(false),[closing,setClosing]=useState(false),[saving,setSaving]=useState(false),[message,setMessage]=useState(''),[errors,setErrors]=useState<Record<string,string>>({}),[storageError,setStorageError]=useState(false);
 const [companies,setCompanies]=useState<CompaniesPage|null>(null),[page,setPage]=useState(1),[retry,setRetry]=useState(0),[companyName,setCompanyName]=useState(''),[initialError,setInitialError]=useState('');
 const invalidFocus=useRef<string|null>(null);
 const focusInvalid=()=>{const id=invalidFocus.current;if(!id)return false;const element=document.getElementById(id);if(!element)return false;invalidFocus.current=null;element.focus({preventScroll:true});element.scrollIntoView({block:'nearest'});return true;};
 const reportErrors=(next:Record<string,string>)=>{setErrors(next);setOpen(true);invalidFocus.current=next.occurred_at?'exchange-date':next.channel?'exchange-channel-phone':next.notes?'exchange-notes':next.company_id?'exchange-company-none':null;const dialogOpen=Boolean(document.querySelector('[data-slot="dialog-content"]'));setClosing(false);if(!dialogOpen)requestAnimationFrame(focusInvalid);};
 const closeRef=useRef<HTMLDivElement>(null),permitted=useRef(true);
 const update=(next:ExchangeDraft)=>{ref.current=next;setDraft(next);if(exchangeDirty(next))setStorageError(!writeExchangeDraft(ownerId,next));else removeExchangeDraft(ownerId,contactId);};
 const denied=(status:string)=>{if(status==='unauthenticated'||status==='forbidden'){permitted.current=false;setCompanies(null);setCompanyName('');window.dispatchEvent(new Event('crm-session-denied'));return true;}return false;};
 useEffect(()=>{if(ref.current)return;const saved=readExchangeDraft(ownerId,contactId);if(saved){ref.current=saved;setDraft(saved);setOpen(true);setMessage('Brouillon d’échange repris dans cet onglet.');}},[ownerId,contactId]);
 useEffect(()=>{active.current=true;permitted.current=true;let epoch=0;
 const load=async()=>{if(!permitted.current)return;const stamp=++epoch;try{const response=await fetch(`/api/contacts/company?id=${encodeURIComponent(contactId)}`,{cache:'no-store',credentials:'same-origin',signal:AbortSignal.timeout(15000)});const result=contactCompanyReadSchema.parse(await response.json());if(!active.current||stamp!==epoch)return;if(denied(result.status))return;if(result.status==='success'){if(!ref.current||!exchangeDirty(ref.current)){const fresh=freshExchangeDraft(contactId,result.relation.company?.id??null);ref.current=fresh;setDraft(fresh);}setInitialError('');}else setInitialError(result.message);}catch{if(active.current&&stamp===epoch)setInitialError('Société actuelle indisponible. Réessayez pour initialiser l’échange.');}};
 load().catch(()=>undefined);const run=()=>load().catch(()=>undefined);const expire=()=>{permitted.current=false;epoch++;setDraft(null);setCompanies(null);setCompanyName('');};const unload=(e:BeforeUnloadEvent)=>{if(ref.current&&exchangeDirty(ref.current))e.preventDefault();};for(const e of ['focus','online','crm-data-changed','crm-session-ready'])window.addEventListener(e,run);window.addEventListener('crm-session-expired',expire);window.addEventListener('beforeunload',unload);return()=>{active.current=false;epoch++;for(const e of ['focus','online','crm-data-changed','crm-session-ready'])window.removeEventListener(e,run);window.removeEventListener('crm-session-expired',expire);window.removeEventListener('beforeunload',unload);};},[ownerId,contactId,retry]);
 useEffect(()=>{let current=true,epoch=0;const load=()=>{if(!permitted.current)return;const stamp=++epoch;setCompanies(null);fetchCompanies(page).then(result=>{if(current&&stamp===epoch&&active.current&&!denied(result.status))setCompanies(result);}).catch(()=>{if(current)setCompanies({status:'unavailable',message:'Liste des sociétés indisponible.'});});};load();for(const e of ['focus','online','crm-data-changed'])window.addEventListener(e,load);return()=>{current=false;for(const e of ['focus','online','crm-data-changed'])window.removeEventListener(e,load);};},[page,retry]);
 const companyId=draft?.values.company_id;
 useEffect(()=>{let current=true,epoch=0;const load=()=>{const stamp=++epoch;if(!companyId){setCompanyName('');return;}fetchCompany(companyId).then(result=>{if(current&&stamp===epoch&&active.current&&!denied(result.status))setCompanyName(result.status==='success'?result.company.name:'Nom indisponible');}).catch(()=>{if(current&&stamp===epoch)setCompanyName('Nom indisponible');});};setCompanyName('');load();for(const e of ['focus','online','crm-data-changed'])window.addEventListener(e,load);return()=>{current=false;for(const e of ['focus','online','crm-data-changed'])window.removeEventListener(e,load);};},[companyId,retry]);
 const change=(field:keyof ExchangeDraft['values'],value:string|null)=>{if(!ref.current)return;invalidFocus.current=null;update({...ref.current,generation:ref.current.generation+1,values:{...ref.current.values,[field]:value,...(field==='local'?{occurrence:''}:{})}});setErrors({});setMessage('');};
 const discard=()=>{if(flight.current)return;removeExchangeDraft(ownerId,contactId);if(ref.current)update(freshExchangeDraft(contactId,ref.current.values.company_id));setOpen(false);setClosing(false);setMessage('');setErrors({});setRetry(n=>n+1);};
 const save=async(force=false):Promise<boolean>=>{
  if(flight.current||!ref.current||!permitted.current)return false;if(!force&&!exchangeDirty(ref.current))return true;
  const current=ref.current;let pending=current.pending;
  if(!pending){const resolved=resolveParisDate(current.values.local,current.values.occurrence||undefined);if('error'in resolved){reportErrors({occurred_at:resolved.error});return false;}
   const parsed=exchangeFieldsSchema.safeParse({contact_id:contactId,company_id:current.values.company_id,occurred_at:resolved.instant,channel:current.values.channel,notes:current.values.notes});
   if(!parsed.success){const next:Record<string,string>={};for(const issue of parsed.error.issues)next[String(issue.path[0])]=issue.path[0]==='channel'?'Choisissez un canal.':issue.message;reportErrors(next);return false;}
   pending={command:{operation:'create',command_id:crypto.randomUUID(),fields:parsed.data},generation:current.generation};update({...current,pending});
  }
  flight.current=true;setSaving(true);onBusyChange(true);setMessage('');try{const result=await sendExchangeCommand(pending.command);if(!active.current)return false;if(denied(result.status))return false;if(result.status==='success'){
   const latest=ref.current;if(latest.pending?.command.command_id!==pending.command.command_id)return false;const next=acknowledgeExchange(latest);update(next);setMessage(exchangeDirty(next)?'Échange enregistré. Votre nouvelle saisie reste à enregistrer.':'Échange enregistré.');window.dispatchEvent(new Event('crm-data-changed'));if(!exchangeDirty(next))setOpen(false);setClosing(false);return !exchangeDirty(next);
  }if(result.status!=='unavailable')update({...ref.current,pending:null});if(result.status==='validation'&&result.field)reportErrors({[result.field]:result.message});setMessage(result.message);setClosing(false);return false;}finally{flight.current=false;if(active.current){setSaving(false);onBusyChange(false);}}
 };
 handle.current={busy:()=>flight.current,focusInvalid,dirty:()=>Boolean(ref.current&&exchangeDirty(ref.current)),hasPending:()=>Boolean(ref.current?.pending),save,discard};
 const candidates=draft?parisCandidates(draft.values.local):[];
 return <section className="space-y-3 border-t pt-5" aria-label="Ajouter un échange" onKeyDown={event=>{if(event.key==='Enter'&&event.target instanceof HTMLInputElement){event.preventDefault();event.stopPropagation();}}}><Button type="button" variant="outline" className="min-h-11" onClick={()=>{if(ref.current&&!exchangeDirty(ref.current))update(freshExchangeDraft(contactId,ref.current.values.company_id));setOpen(true);}}>Ajouter un échange</Button>{initialError?<div role="alert"><p className="text-sm">{initialError}</p><Button type="button" variant="outline" onClick={()=>setRetry(n=>n+1)}>Recharger la société initiale</Button></div>:null}
 <div hidden={!open} className="space-y-4">{!draft?<Skeleton className="h-36 w-full"/>:<fieldset className="space-y-4" disabled={!permitted.current} aria-busy={saving}><legend className="mb-3 text-sm font-medium">Nouvel échange</legend><div className="space-y-2"><Label htmlFor="exchange-date">Date et heure de Paris</Label><Input id="exchange-date" type="datetime-local" className="min-h-11 text-base" value={draft.values.local} aria-invalid={Boolean(errors.occurred_at)} aria-describedby="exchange-date-help exchange-error-occurred_at" onChange={e=>change('local',e.target.value)}/><p id="exchange-date-help" className="text-xs text-muted-foreground">Europe/Paris. Les dates futures sont refusées.</p>{candidates.length>1?<div className="space-y-2"><p className="text-sm">Choisissez l’occurrence de cette heure :</p>{candidates.map((candidate,index)=><Button key={candidate.instant} type="button" className="min-h-11" variant={draft.values.occurrence===candidate.instant?'default':'outline'} aria-pressed={draft.values.occurrence===candidate.instant} onClick={()=>change('occurrence',candidate.instant)}>{index+1} · {candidate.offset}</Button>)}</div>:null}<p id="exchange-error-occurred_at" className="text-sm text-destructive" role={errors.occurred_at?'alert':undefined}>{errors.occurred_at}</p></div>
 <fieldset className="space-y-2" aria-describedby="exchange-error-channel"><legend className="text-sm font-medium">Canal</legend><div className="flex flex-wrap gap-2">{Object.entries(EXCHANGE_CHANNEL_LABELS).map(([value,label])=><Button key={value} id={`exchange-channel-${value}`} type="button" className="min-h-11" variant={draft.values.channel===value?'default':'outline'} aria-pressed={draft.values.channel===value} onClick={()=>change('channel',value)}>{label}</Button>)}</div><p id="exchange-error-channel" role={errors.channel?'alert':undefined} className="text-sm text-destructive">{errors.channel}</p></fieldset>
 <div className="space-y-2"><Label htmlFor="exchange-notes">Notes <span className="text-xs text-muted-foreground">Facultatif</span></Label><Textarea id="exchange-notes" className="min-h-24 text-base [field-sizing:fixed]" rows={4} value={draft.values.notes} aria-invalid={Boolean(errors.notes)} aria-describedby="exchange-error-notes" onChange={e=>change('notes',e.target.value)}/><p id="exchange-error-notes" role={errors.notes?'alert':undefined} className="text-sm text-destructive">{errors.notes}</p><p className="text-xs text-muted-foreground">20 000 caractères maximum.</p></div>
 <fieldset className="space-y-2"><legend className="text-sm font-medium">Société historique · facultatif</legend><p className="text-sm [overflow-wrap:anywhere]">Sélection : {companyId?companyName||'Chargement du nom…':'Aucune société'}</p><Button id="exchange-company-none" type="button" variant={companyId?'outline':'default'} aria-pressed={!companyId} className="min-h-11" onClick={()=>change('company_id',null)}>Sans société</Button>{companies?.status==='success'?<><ul className="space-y-1">{companies.companies.map(company=><li key={company.id}><Button type="button" variant={companyId===company.id?'default':'outline'} aria-pressed={companyId===company.id} className="h-auto min-h-11 w-full justify-start whitespace-normal text-left" onClick={()=>change('company_id',company.id)}>{company.name}</Button></li>)}</ul>{companies.total>25?<div className="flex flex-wrap gap-2"><Button type="button" variant="outline" disabled={page===1} onClick={()=>setPage(p=>p-1)}>Sociétés historiques précédentes</Button><Button type="button" variant="outline" disabled={page*25>=companies.total} onClick={()=>setPage(p=>p+1)}>Sociétés historiques suivantes</Button></div>:null}</>:companies?<><p role="alert" className="text-sm">{companies.message}</p><Button type="button" variant="outline" onClick={()=>setRetry(n=>n+1)}>Recharger les sociétés historiques</Button></>:<Skeleton className="h-11 w-full"/>}<p className="text-xs text-muted-foreground">Ce lien restera attaché à l’échange si le contact change de société.</p>{errors.company_id?<p role="alert" className="text-sm text-destructive">{errors.company_id}</p>:null}</fieldset>
 <div className="flex flex-wrap gap-2"><Button type="button" className="min-h-11" disabled={saving} onClick={()=>save(true).catch(()=>setMessage('Confirmation indisponible. Votre saisie est conservée.'))}>{saving?'Enregistrement…':draft.pending?'Réessayer la confirmation':'Ajouter'}</Button><Button type="button" variant="outline" className="min-h-11" disabled={saving} onClick={()=>{if(exchangeDirty(draft))setClosing(true);else setOpen(false);}}>Annuler l’échange</Button></div></fieldset>}</div>{storageError?<p role="alert" className="text-sm text-destructive">Stockage indisponible. Gardez cet onglet ouvert jusqu’à confirmation.</p>:null}{message?<p role="status" className="text-sm" data-exchange-message>{message}</p>:null}
 <Dialog open={closing} onOpenChange={setClosing}><DialogContent ref={closeRef} tabIndex={-1} onCloseAutoFocus={event=>{if(focusInvalid())event.preventDefault();}} onOpenAutoFocus={e=>{e.preventDefault();closeRef.current?.focus();}}><DialogHeader><DialogTitle>Conserver cet échange ?</DialogTitle><DialogDescription>La saisie n’est pas encore confirmée.</DialogDescription></DialogHeader><DialogFooter className="sm:flex-wrap"><Button type="button" disabled={saving} onClick={()=>save().catch(()=>setMessage('Confirmation indisponible.'))}>Enregistrer</Button><Button type="button" variant="outline" disabled={saving} onClick={discard}>Abandonner</Button><Button type="button" variant="ghost" onClick={()=>setClosing(false)}>Continuer la saisie</Button></DialogFooter></DialogContent></Dialog></section>;
}
