'use client';
import {useEffect,useRef,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Label} from '@/components/ui/label';
import {Textarea} from '@/components/ui/textarea';
import {Skeleton} from '@/components/ui/skeleton';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription,DialogFooter} from '@/components/ui/dialog';
import {fetchCompanies,fetchCompany} from '@/lib/companies-transport';
import {fetchContacts,fetchContact} from '@/lib/contacts-transport';
import {type CompaniesPage} from '@/lib/validations/companies';
import {type ContactsPage} from '@/lib/validations/contacts';
import {exchangeFieldsSchema,EXCHANGE_CHANNEL_LABELS,type Exchange,type ExchangeField,type ExchangeResult} from '@/lib/validations/exchanges';
import {parisCandidates,resolveParisDate,formatExchangeDate} from '@/lib/exchange-date';
import {readExchange,sendExchangeCommand} from '@/lib/exchanges-transport';
import {revalidateExchangeUpdate,acknowledgeExchangeUpdate,changedExchangeFields,exchangeUpdateCommand,exchangeUpdateDirty,freshExchangeUpdate,readExchangeUpdate,removeExchangeUpdate,writeExchangeUpdate,EXCHANGE_EDIT_FIELDS,type ExchangeUpdateDraft} from '@/lib/exchanges-drafts';
import {type ExchangeEditorHandle} from './exchange-editor';
const labels:Record<ExchangeField,string>={occurred_at:'Date et heure',channel:'Canal',notes:'Notes',contact_id:'Contact',company_id:'Société historique'};
export function ExchangeUpdateEditor({ownerId,exchange,handle,onBusyChange,onDone}:{ownerId:string;exchange:Exchange;handle:React.RefObject<ExchangeEditorHandle|null>;onBusyChange:(busy:boolean)=>void;onDone:(saved?:boolean)=>void}){
 const [draft,setDraft]=useState(()=>readExchangeUpdate(ownerId,exchange.id)??freshExchangeUpdate(exchange));const ref=useRef(draft),flight=useRef(false),active=useRef(true),allowed=useRef(true);
 const cleanupBlocked=useRef(false);
 const [saving,setSaving]=useState(false),[message,setMessage]=useState(''),[storageError,setStorageError]=useState(false),[errors,setErrors]=useState<Partial<Record<ExchangeField,string>>>({}),[closing,setClosing]=useState(false);
 const [conflict,setConflict]=useState<Extract<ExchangeResult,{status:'conflict'}>|null>(null),[choices,setChoices]=useState<Partial<Record<ExchangeField,'mine'|'server'>>>({});
 const [companies,setCompanies]=useState<CompaniesPage|null>(null),[contacts,setContacts]=useState<ContactsPage|null>(null),[companyPage,setCompanyPage]=useState(1),[contactPage,setContactPage]=useState(1),[retry,setRetry]=useState(0),[companiesLoading,setCompaniesLoading]=useState(true),[contactsLoading,setContactsLoading]=useState(true),[companyName,setCompanyName]=useState(''),[contactName,setContactName]=useState('');
 const invalid=useRef<ExchangeField|null>(null),dialogRef=useRef<HTMLDivElement>(null);const id=(field:string)=>`exchange-${exchange.id}-${field}`;
 const focusInvalid=()=>{if(!invalid.current)return false;const element=document.getElementById(id(invalid.current));if(!element)return false;invalid.current=null;element.focus({preventScroll:true});element.scrollIntoView({block:'nearest'});return true;};
 const update=(next:ExchangeUpdateDraft)=>{ref.current=next;setDraft(next);if(exchangeUpdateDirty(next)){const stored=writeExchangeUpdate(ownerId,next);setStorageError(!stored||cleanupBlocked.current);}else{cleanupBlocked.current=!removeExchangeUpdate(ownerId,next.base.id);setStorageError(cleanupBlocked.current);}};
 const remove=()=>{const removed=removeExchangeUpdate(ownerId,exchange.id);cleanupBlocked.current=!removed;setStorageError(!removed);if(!removed){setClosing(false);setMessage('Brouillon non effacé du stockage. Gardez la fiche ouverte et réessayez.');}return removed;};
 const denied=(status:string)=>{if(status==='unauthenticated'||status==='forbidden'){allowed.current=false;window.dispatchEvent(new Event('crm-session-denied'));return true;}return false;};
 const report=(next:Partial<Record<ExchangeField,string>>)=>{setErrors(next);invalid.current=EXCHANGE_EDIT_FIELDS.find(field=>next[field])??null;setClosing(false);if(!document.querySelector('[data-slot="dialog-content"]'))requestAnimationFrame(focusInvalid);};
 useEffect(()=>{active.current=true;const unload=(event:BeforeUnloadEvent)=>{if(exchangeUpdateDirty(ref.current)||cleanupBlocked.current)event.preventDefault();};const expire=()=>{allowed.current=false;setCompanies(null);setContacts(null);};window.addEventListener('beforeunload',unload);window.addEventListener('crm-session-expired',expire);return()=>{active.current=false;window.removeEventListener('beforeunload',unload);window.removeEventListener('crm-session-expired',expire);handle.current=null;};},[handle]);
 useEffect(()=>{let current=true,epoch=0;const refresh=async()=>{if(!allowed.current||flight.current)return;const stamp=++epoch;const result=await readExchange(exchange.id);if(!current||stamp!==epoch||!allowed.current||flight.current)return;if(denied(result.status))return;if(result.status==='success')update(revalidateExchangeUpdate(ref.current,result.exchange));else setMessage(result.message);};const run=()=>refresh().catch(()=>setMessage('Relecture indisponible. Votre saisie est conservée.'));run();for(const event of ['focus','online','crm-data-changed'])window.addEventListener(event,run);return()=>{current=false;epoch++;for(const event of ['focus','online','crm-data-changed'])window.removeEventListener(event,run);};},[exchange.id,ownerId]);
 useEffect(()=>{let current=true;setCompaniesLoading(true);fetchCompanies(companyPage).then(result=>{if(current&&allowed.current&&!denied(result.status))setCompanies(result);}).catch(()=>{if(current)setCompanies({status:'unavailable',message:'Liste des sociétés indisponible.'});}).finally(()=>{if(current)setCompaniesLoading(false);});return()=>{current=false;};},[companyPage,retry]);
 useEffect(()=>{let current=true;setContactsLoading(true);fetchContacts(contactPage).then(result=>{if(current&&allowed.current&&!denied(result.status))setContacts(result);}).catch(()=>{if(current)setContacts({status:'unavailable',message:'Liste des contacts indisponible.'});}).finally(()=>{if(current)setContactsLoading(false);});return()=>{current=false;};},[contactPage,retry]);
 useEffect(()=>{let current=true;setCompanyName('');setContactName('');if(draft.values.company_id)fetchCompany(draft.values.company_id).then(result=>{if(current&&!denied(result.status))setCompanyName(result.status==='success'?result.company.name:'Nom indisponible');}).catch(()=>setCompanyName('Nom indisponible'));fetchContact(draft.values.contact_id).then(result=>{if(current&&!denied(result.status))setContactName(result.status==='success'?[result.contact.first_name,result.contact.last_name].filter(Boolean).join(' '):'Nom indisponible');}).catch(()=>setContactName('Nom indisponible'));return()=>{current=false;};},[draft.values.contact_id,draft.values.company_id,retry]);
 const change=(field:keyof ExchangeUpdateDraft['values'],value:string|null)=>{const versionField=field==='local'||field==='occurrence'?'occurred_at':field;const current=ref.current;update({...current,values:{...current.values,[field]:value,...(field==='local'?{occurrence:''}:{})},generations:{...current.generations,[versionField]:current.generations[versionField]+1}});invalid.current=null;setErrors({});setMessage('');};
 const discard=()=>{if(flight.current||!remove())return false;ref.current=freshExchangeUpdate(ref.current.base);setDraft(ref.current);setClosing(false);onDone();return true;};
 const save=async():Promise<boolean>=>{
  if(flight.current||!allowed.current||conflict)return false;if(!exchangeUpdateDirty(ref.current)){if(!remove())return false;onDone();return true;}
  let pending=ref.current.pending;
  if(!pending){const current=ref.current;const dateChanged=changedExchangeFields(current).includes('occurred_at');const resolved=dateChanged?resolveParisDate(current.values.local,current.values.occurrence||undefined):{instant:current.base.occurred_at};if('error'in resolved){report({occurred_at:resolved.error});return false;}
   const parsed=exchangeFieldsSchema.safeParse({contact_id:current.values.contact_id,company_id:current.values.company_id,occurred_at:resolved.instant,channel:current.values.channel,notes:current.values.notes});if(!parsed.success){const next:Partial<Record<ExchangeField,string>>={};for(const issue of parsed.error.issues)next[issue.path[0] as ExchangeField]=issue.message;report(next);return false;}
   pending={command:exchangeUpdateCommand(current,resolved.instant),generations:{...current.generations}};update({...current,pending});
  }
  flight.current=true;setSaving(true);onBusyChange(true);setMessage('');try{
   const result=await sendExchangeCommand(pending.command);
   // Projections are invalidated even when the originating editor has unmounted.
   if(result.status==='success')window.dispatchEvent(new Event('crm-data-changed'));
   if(!active.current)return false;if(denied(result.status))return false;
   if(result.status==='success'){
    const actual=await readExchange(exchange.id);if(!active.current)return false;if(denied(actual.status))return false;
    if(actual.status!=='success'){setMessage('Correction reçue. Relecture indisponible ; réessayez la confirmation.');setClosing(false);return false;}
    if(ref.current.pending?.command.command_id!==pending.command.command_id)return false;
    const next=acknowledgeExchangeUpdate(ref.current,result.exchange,actual.exchange);if(!exchangeUpdateDirty(next)&&!remove()){update({...ref.current,pending:{...pending,confirmed:result.exchange}});return false;}if(exchangeUpdateDirty(next))update(next);else{ref.current=next;setDraft(next);}setClosing(false);window.dispatchEvent(new Event('crm-data-changed'));
    setMessage(exchangeUpdateDirty(next)?'Correction enregistrée. Votre nouvelle saisie reste à enregistrer.':'Correction enregistrée.');if(!exchangeUpdateDirty(next))onDone(true);return !exchangeUpdateDirty(next);
   }
   if(result.status!=='unavailable')update({...ref.current,pending:null});if(result.status==='conflict'){setConflict(result);setChoices({});}if(result.status==='validation'&&result.field)report({[result.field]:result.message});setMessage(result.message);setClosing(false);return false;
  }finally{flight.current=false;if(active.current){setSaving(false);onBusyChange(false);}}
 };
 handle.current={dirty:()=>exchangeUpdateDirty(ref.current)||cleanupBlocked.current,busy:()=>flight.current,hasPending:()=>Boolean(ref.current.pending),focusInvalid,save,discard};
 const resolve=()=>{if(!conflict||conflict.conflicting_fields.some(field=>!choices[field]))return;const current=ref.current,next=freshExchangeUpdate(conflict.exchange),changed=new Set([...changedExchangeFields(current),...conflict.conflicting_fields.filter(field=>choices[field]==='mine')]);for(const field of changed){if(choices[field]==='server')continue;if(field==='occurred_at'){next.values.local=current.values.local;next.values.occurrence=current.values.occurrence;}else Object.assign(next.values,{[field]:current.values[field]});}update({...next,generations:current.generations});setConflict(null);setChoices({});setMessage('Choix préparés. Enregistrez pour confirmer.');};
 const error=(field:ExchangeField)=><p id={id(`error-${field}`)} role={errors[field]?'alert':undefined} className="text-sm text-destructive">{errors[field]}</p>;
 const serverValue=(field:ExchangeField)=>{if(!conflict)return '';if(field==='occurred_at')return formatExchangeDate(conflict.exchange.occurred_at);if(field==='channel')return EXCHANGE_CHANNEL_LABELS[conflict.exchange.channel];if(field==='company_id')return conflict.exchange.company_name|| (conflict.exchange.company_id?'Société enregistrée':'Sans société');if(field==='contact_id')return conflict.exchange.contact_name||'Contact enregistré';return conflict.exchange.notes||'Sans note';};
 return <section aria-label="Corriger un échange" data-exchange-editor={exchange.id} className="space-y-4 rounded-md border p-3" onKeyDown={event=>{if(event.key==='Enter'&&event.target instanceof HTMLInputElement){event.preventDefault();event.stopPropagation();}}}>
 <h3 className="text-sm font-medium">Corriger cet échange</h3><fieldset className="space-y-4" disabled={!allowed.current} aria-busy={saving}>
 <div className="space-y-2"><Label htmlFor={id('occurred_at')}>Date et heure de Paris</Label><Input id={id('occurred_at')} type="datetime-local" className="min-h-11 text-base" value={draft.values.local} onChange={e=>change('local',e.target.value)} aria-invalid={Boolean(errors.occurred_at)} aria-describedby={id('error-occurred_at')}/><p className="text-xs text-muted-foreground">Europe/Paris. Les dates futures sont refusées.</p>{parisCandidates(draft.values.local).length>1?<div className="flex flex-wrap gap-2">{parisCandidates(draft.values.local).map((candidate,index)=><Button className="min-h-11" key={candidate.instant} type="button" variant={draft.values.occurrence===candidate.instant?'default':'outline'} aria-pressed={draft.values.occurrence===candidate.instant} onClick={()=>change('occurrence',candidate.instant)}>{index+1} · {candidate.offset}</Button>)}</div>:null}{error('occurred_at')}</div>
 <fieldset className="space-y-2" aria-describedby={id('error-channel')}><legend className="text-sm font-medium">Canal</legend><div className="flex flex-wrap gap-2">{Object.entries(EXCHANGE_CHANNEL_LABELS).map(([value,label],index)=><Button id={index===0?id('channel'):undefined} aria-describedby={id('error-channel')} type="button" key={value} variant={draft.values.channel===value?'default':'outline'} aria-pressed={draft.values.channel===value} className="min-h-11" onClick={()=>change('channel',value)}>{label}</Button>)}</div>{error('channel')}</fieldset>
 <div className="space-y-2"><Label htmlFor={id('notes')}>Notes · facultatif</Label><Textarea id={id('notes')} className="min-h-24 text-base [field-sizing:fixed]" value={draft.values.notes} onChange={e=>change('notes',e.target.value)} aria-invalid={Boolean(errors.notes)} aria-describedby={id('error-notes')}/>{error('notes')}<p className="text-xs text-muted-foreground">20 000 caractères maximum.</p></div>
 <fieldset className="space-y-2" disabled={contactsLoading} aria-busy={contactsLoading} aria-describedby={id('error-contact_id')}><legend className="text-sm font-medium">Contact obligatoire</legend><p className="text-sm [overflow-wrap:anywhere]">Sélection : {contactName||'Chargement du nom…'}</p>{contactsLoading?<Skeleton className="h-11 w-full"/>:contacts?.status==='success'?<><ul className="space-y-1">{contacts.contacts.map((contact,index)=><li key={contact.id}><Button id={index===0?id('contact_id'):undefined} aria-describedby={id('error-contact_id')} type="button" variant={draft.values.contact_id===contact.id?'default':'outline'} aria-pressed={draft.values.contact_id===contact.id} className="h-auto min-h-11 w-full justify-start whitespace-normal text-left" onClick={()=>change('contact_id',contact.id)}>{[contact.first_name,contact.last_name].filter(Boolean).join(' ')}</Button></li>)}</ul>{contacts.total>25?<div className="flex gap-2"><Button className="min-h-11" type="button" variant="outline" disabled={contactPage===1} onClick={()=>{setContactsLoading(true);setContactPage(p=>p-1);}}>Contacts précédents</Button><Button className="min-h-11" type="button" variant="outline" disabled={contactPage*25>=contacts.total} onClick={()=>{setContactsLoading(true);setContactPage(p=>p+1);}}>Contacts suivants</Button></div>:null}</>:contacts?<p role="alert">{contacts.message}</p>:<Skeleton className="h-11 w-full"/>}{error('contact_id')}<p className="text-xs text-muted-foreground">Changer le contact conserve la société historique sélectionnée.</p></fieldset>
 <fieldset className="space-y-2" disabled={companiesLoading} aria-busy={companiesLoading} aria-describedby={id('error-company_id')}><legend className="text-sm font-medium">Société historique · facultatif</legend><p className="text-sm [overflow-wrap:anywhere]">Sélection : {draft.values.company_id?companyName||'Chargement du nom…':'Aucune société'}</p><Button id={id('company_id')} aria-describedby={id('error-company_id')} type="button" variant={draft.values.company_id?'outline':'default'} aria-pressed={!draft.values.company_id} className="min-h-11" onClick={()=>change('company_id',null)}>Sans société</Button>{companiesLoading?<Skeleton className="h-11 w-full"/>:companies?.status==='success'?<><ul className="space-y-1">{companies.companies.map(company=><li key={company.id}><Button aria-describedby={id('error-company_id')} type="button" variant={draft.values.company_id===company.id?'default':'outline'} aria-pressed={draft.values.company_id===company.id} className="h-auto min-h-11 w-full justify-start whitespace-normal text-left" onClick={()=>change('company_id',company.id)}>{company.name}</Button></li>)}</ul>{companies.total>25?<div className="flex gap-2"><Button className="min-h-11" type="button" variant="outline" disabled={companyPage===1} onClick={()=>{setCompaniesLoading(true);setCompanyPage(p=>p-1);}}>Sociétés précédentes</Button><Button className="min-h-11" type="button" variant="outline" disabled={companyPage*25>=companies.total} onClick={()=>{setCompaniesLoading(true);setCompanyPage(p=>p+1);}}>Sociétés suivantes</Button></div>:null}</>:companies?<p role="alert">{companies.message}</p>:<Skeleton className="h-11 w-full"/>}{error('company_id')}</fieldset>
 {companies?.status!=='success'||contacts?.status!=='success'?<Button className="min-h-11" type="button" variant="outline" onClick={()=>setRetry(n=>n+1)}>Recharger les listes</Button>:null}
 {conflict?<div className="space-y-3" role="alert"><p className="text-sm">Certains champs ont changé ailleurs. Choisissez pour chacun.</p>{conflict.conflicting_fields.map(field=><fieldset key={field} className="space-y-2"><legend className="text-sm font-medium">{labels[field]}</legend><p className="whitespace-pre-wrap text-xs [overflow-wrap:anywhere]">Valeur enregistrée : {serverValue(field)}</p><div className="flex flex-wrap gap-2"><Button className="min-h-11" type="button" aria-pressed={choices[field]==='mine'} variant={choices[field]==='mine'?'default':'outline'} onClick={()=>setChoices(previous=>({...previous,[field]:'mine'}))}>Garder ma saisie · {labels[field]}</Button><Button className="min-h-11" type="button" aria-pressed={choices[field]==='server'} variant={choices[field]==='server'?'default':'outline'} onClick={()=>setChoices(previous=>({...previous,[field]:'server'}))}>Garder la valeur enregistrée · {labels[field]}</Button></div></fieldset>)}<Button className="min-h-11" type="button" disabled={conflict.conflicting_fields.some(field=>!choices[field])} onClick={resolve}>Préparer les choix</Button></div>:null}
 <div className="flex flex-wrap gap-2"><Button className="min-h-11" type="button" disabled={saving||Boolean(conflict)} onClick={()=>save().catch(()=>setMessage('Confirmation indisponible. Votre saisie est conservée.'))}>{saving?'Enregistrement…':draft.pending?'Réessayer la confirmation':'Enregistrer la correction'}</Button><Button className="min-h-11" type="button" variant="outline" disabled={saving} onClick={()=>exchangeUpdateDirty(ref.current)||cleanupBlocked.current?setClosing(true):discard()}>Annuler la correction</Button></div>
 </fieldset>{storageError?<p role="alert" className="text-sm text-destructive">Stockage indisponible. Gardez cet onglet ouvert jusqu’à confirmation.</p>:null}{message?<p role="status" data-exchange-update-message className="text-sm">{message}</p>:null}
 <Dialog open={closing} onOpenChange={setClosing}><DialogContent ref={dialogRef} tabIndex={-1} onOpenAutoFocus={event=>{event.preventDefault();dialogRef.current?.focus();}} onCloseAutoFocus={event=>{if(focusInvalid())event.preventDefault();}}><DialogHeader><DialogTitle>Conserver cette correction ?</DialogTitle><DialogDescription>La correction n’est pas encore confirmée.</DialogDescription></DialogHeader><DialogFooter><Button className="min-h-11" type="button" disabled={saving||Boolean(conflict)} onClick={()=>save().catch(()=>setMessage('Confirmation indisponible.'))}>Enregistrer</Button><Button className="min-h-11" type="button" variant="outline" disabled={saving} onClick={discard}>Abandonner</Button><Button className="min-h-11" type="button" variant="ghost" onClick={()=>setClosing(false)}>Continuer la saisie</Button></DialogFooter></DialogContent></Dialog>
 </section>;
}
