'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Skeleton} from '@/components/ui/skeleton';
import {fetchOpportunities,type OpportunityContext} from '@/lib/opportunities-transport';
import {OPPORTUNITY_STAGE_LABELS,type OpportunitiesPage} from '@/lib/validations/opportunities';
type OpportunityLinksProps={contactId?:string;companyId?:string;onNavigate?:(href:string)=>void;compact?:boolean;count?:number};
export function OpportunityLinks(props:OpportunityLinksProps){if(props.compact)return <div data-contact-opportunities={props.contactId} onClick={event=>event.stopPropagation()}>{props.count===undefined?<span className="text-xs text-muted-foreground">Indisponible</span>:props.count===0?<span className="text-xs text-muted-foreground">—</span>:<a href={`/pipeline?contact_id=${props.contactId}`} className="inline-flex min-h-11 items-center text-sm underline">{props.count} opportunité{props.count>1?'s':''}</a>}</div>;return <OpportunityContextLinks key={props.contactId?`contact:${props.contactId}`:`company:${props.companyId}`} {...props}/>;}
function OpportunityContextLinks({contactId,companyId,onNavigate}:OpportunityLinksProps){
 const [result,setResult]=useState<OpportunitiesPage|null>(null),[page,setPage]=useState(1),[loading,setLoading]=useState(false);const epoch=useRef(0),allowed=useRef(true);const context:OpportunityContext=contactId?{contact_id:contactId}:{company_id:companyId!};
 const refresh=useCallback(async()=>{if(!allowed.current)return;const stamp=++epoch.current;setLoading(true);const result=await fetchOpportunities(page,contactId?{contact_id:contactId}:{company_id:companyId!});if(!allowed.current||stamp!==epoch.current)return;if(result.status==='unauthenticated'||result.status==='forbidden'){window.dispatchEvent(new Event('crm-session-denied'));return;}if(result.status==='success'&&page>Math.max(1,Math.ceil(result.total/25))){setPage(Math.max(1,Math.ceil(result.total/25)));return;}setResult(result);setLoading(false);},[contactId,companyId,page]);
 useEffect(()=>{const run=()=>refresh().catch(()=>setLoading(false));run();const expire=()=>{allowed.current=false;epoch.current++;setResult(null);};for(const event of ['focus','online','crm-data-changed'])window.addEventListener(event,run);window.addEventListener('crm-session-expired',expire);return()=>{epoch.current++;for(const event of ['focus','online','crm-data-changed'])window.removeEventListener(event,run);window.removeEventListener('crm-session-expired',expire);};},[refresh]);
 const link=(href:string,text:string)=><a href={href} className="inline-flex min-h-11 max-w-full items-center whitespace-normal text-sm underline [overflow-wrap:anywhere]" onClick={event=>{event.stopPropagation();if(onNavigate&&!event.metaKey&&!event.ctrlKey&&!event.shiftKey&&!event.altKey){event.preventDefault();onNavigate(href);}}}>{text}</a>;

 return <section aria-label="Opportunités liées" aria-busy={loading} className="space-y-3 border-t pt-5"><h2 className="text-sm font-medium">Opportunités{result?.status==='success'?` (${result.total})`:''}</h2>{link(`/pipeline?panel=new&${new URLSearchParams(context)}`,'Nouvelle opportunité')}{!result?<Skeleton className="h-20 w-full"/>:result.status!=='success'?<><p role="alert" className="text-sm">{result.message}</p><Button type="button" variant="outline" className="min-h-11" onClick={()=>refresh().catch(()=>undefined)}>Réessayer les opportunités</Button></>:!result.total?<p className="text-sm text-muted-foreground">Aucune opportunité liée.</p>:<><ul className="space-y-1">{result.opportunities.map(item=><li key={item.id} data-related-opportunity={item.id}>{link(`/pipeline?panel=${item.id}`,item.title)}<p className="text-xs text-muted-foreground">{OPPORTUNITY_STAGE_LABELS[item.stage]}</p></li>)}</ul>{result.total>25?<div className="flex flex-wrap gap-2"><Button type="button" variant="outline" className="min-h-11" disabled={loading||page===1} onClick={()=>setPage(page=>page-1)}>Opportunités précédentes</Button><Button type="button" variant="outline" className="min-h-11" disabled={loading||page*25>=result.total} onClick={()=>setPage(page=>page+1)}>Opportunités suivantes</Button><span className="text-xs">{page} / {Math.ceil(result.total/25)}</span></div>:null}</>}</section>;
}
