'use client';
import {useCallback,useEffect,useImperativeHandle,useRef,useState,useSyncExternalStore} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Label} from '@/components/ui/label';
import {Textarea} from '@/components/ui/textarea';
import {Skeleton} from '@/components/ui/skeleton';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription,DialogFooter} from '@/components/ui/dialog';
import {fetchContacts,fetchContact} from '@/lib/contacts-transport';
import {type ContactsPage} from '@/lib/validations/contacts';
import {type OpportunityStore} from '@/lib/opportunities-cache';
import {OPPORTUNITY_EDIT_FIELDS,type OpportunityEditField} from '@/lib/opportunities-drafts';
import {OPPORTUNITY_STAGE_LABELS,centsToDecimal} from '@/lib/validations/opportunities';
export type OpportunityEditorHandle={requestClose:()=>void};
export const OPPORTUNITY_FIELD_LABELS:Record<OpportunityEditField,string>={title:'Titre',amount_cents:'Montant EUR HT',notes:'Notes',stage:'Étape',company_id:'Société',primary_contact_id:'Contact principal'};
export function OpportunityEditor({target,store,handle,onClose,onCancelClose}:{target:string;store:OpportunityStore;handle:React.RefObject<OpportunityEditorHandle|null>;onClose:()=>void;onCancelClose:()=>void}){
 const subscribe=useCallback((listener:()=>void)=>store.subscribe(target,listener),[store,target]);const state=useSyncExternalStore(subscribe,()=>store.get(target),()=>store.get(target));const draft=state.draft;
 const [closing,setClosing]=useState(false),[choices,setChoices]=useState<Partial<Record<OpportunityEditField,'mine'|'server'>>>({});const container=useRef<HTMLDivElement>(null),invalid=useRef<OpportunityEditField|null>(null),preventBlur=useRef(false);
 const [contacts,setContacts]=useState<ContactsPage|null>(null),[contactPage,setContactPage]=useState(1),[loading,setLoading]=useState(true),[retry,setRetry]=useState(0),[contactName,setContactName]=useState('');
 useEffect(()=>{let frame:number|undefined;const release=()=>{if(frame!==undefined)cancelAnimationFrame(frame);frame=requestAnimationFrame(()=>{preventBlur.current=false;});};window.addEventListener('pointerup',release,true);window.addEventListener('pointercancel',release,true);return()=>{window.removeEventListener('pointerup',release,true);window.removeEventListener('pointercancel',release,true);if(frame!==undefined)cancelAnimationFrame(frame);preventBlur.current=false;};},[]);
 const id=(field:string)=>`opportunity-${field}`;
 const denied=(status:string)=>{if(status==='unauthenticated'||status==='forbidden')window.dispatchEvent(new Event('crm-session-denied'));};
 useEffect(()=>{let active=true;setLoading(true);fetchContacts(contactPage).then(result=>{if(!active)return;denied(result.status);setContacts(result);setLoading(false);}).catch(()=>{if(active)setLoading(false);});return()=>{active=false;};},[contactPage,retry]);
 useEffect(()=>{let active=true;setContactName('');if(draft.values.primary_contact_id)fetchContact(draft.values.primary_contact_id).then(result=>{if(active){denied(result.status);setContactName(result.status==='success'?[result.contact.first_name,result.contact.last_name].filter(Boolean).join(' '):'Nom indisponible');}}).catch(()=>{if(active)setContactName('Nom indisponible');});return()=>{active=false;};},[draft.values.primary_contact_id,retry]);
 const focusInvalid=()=>{const first=invalid.current??OPPORTUNITY_EDIT_FIELDS.find(field=>state.errors[field]);if(!first)return false;const element=document.getElementById(id(first));if(!element)return false;element.focus({preventScroll:true});element.scrollIntoView({block:'nearest'});invalid.current=null;return true;};
 const cancel=()=>{setClosing(false);onCancelClose();};
 const requestClose=()=>{preventBlur.current=true;if(store.busy(target)||store.dirty(target))setClosing(true);else onClose();requestAnimationFrame(()=>{preventBlur.current=false;});};useImperativeHandle(handle,()=>({requestClose}));
 useEffect(()=>{const unload=(event:BeforeUnloadEvent)=>{if(store.dirty(target)||store.busy(target))event.preventDefault();};window.addEventListener('beforeunload',unload);return()=>window.removeEventListener('beforeunload',unload);},[store,target]);
 const save=async(closeAfter=false,fields?:OpportunityEditField[])=>{const result=await store.save(target,fields??(!closeAfter&&store.get(target).draft.pending?[]:undefined));if(closeAfter){if(result&&!store.dirty(target)&&!store.busy(target))onClose();else {setClosing(false);onCancelClose();invalid.current=OPPORTUNITY_EDIT_FIELDS.find(field=>store.get(target).errors[field])??null;requestAnimationFrame(focusInvalid);}}else if(!result){invalid.current=OPPORTUNITY_EDIT_FIELDS.find(field=>store.get(target).errors[field])??null;if(invalid.current)requestAnimationFrame(focusInvalid);}return result;};
 const blur=(field:OpportunityEditField)=>{if(draft.base&&!preventBlur.current&&!closing)save(false,[field]).catch(onCancelClose);};
 const select=(field:OpportunityEditField,value:string|null)=>{store.change(target,field,value);if(draft.base)save(false,[field]).catch(onCancelClose);};
 const error=(field:OpportunityEditField)=><p id={id(`error-${field}`)} role={state.errors[field]?'alert':undefined} className="text-sm text-destructive">{state.errors[field]}</p>;
 const conflictFields=state.conflict?.conflicting_fields??[];
 const conflictValue=(field:OpportunityEditField)=>{const opportunity=state.conflict!.opportunity;if(field==='company_id')return opportunity.company_id===null?'Aucune société':opportunity.company_name||'Nom de société indisponible';if(field==='primary_contact_id')return opportunity.primary_contact_id===null?'Aucun contact principal':opportunity.contact_name||'Nom du contact indisponible';if(field==='amount_cents')return centsToDecimal(opportunity.amount_cents)||'Non renseigné';if(field==='stage')return OPPORTUNITY_STAGE_LABELS[opportunity.stage];return opportunity[field];};
 return <><div data-opportunity-editor className="space-y-5 px-5 pb-5" aria-busy={state.busy}>
 <p className="text-xs text-muted-foreground">{draft.base?'Les champs modifiés sont enregistrés à leur sortie.':'Renseignez le titre, puis ajoutez l’opportunité.'}</p>
 {(['title','amount_cents','notes'] as const).map(field=><div key={field} className="space-y-2"><Label htmlFor={id(field)}>{OPPORTUNITY_FIELD_LABELS[field]}{field==='title'?'':' · facultatif'}</Label>{field==='notes'?<Textarea id={id(field)} className="min-h-28 text-base [field-sizing:fixed]" value={draft.values[field]} onChange={event=>store.change(target,field,event.target.value)} onBlur={()=>blur(field)} aria-invalid={Boolean(state.errors[field])} aria-describedby={id(`error-${field}`)}/>:<Input id={id(field)} type="text" inputMode={field==='amount_cents'?'decimal':undefined} className="min-h-11 text-base" value={draft.values[field]} onChange={event=>store.change(target,field,event.target.value)} onBlur={()=>blur(field)} aria-invalid={Boolean(state.errors[field])} aria-describedby={id(`error-${field}`)}/>} {error(field)}{field==='amount_cents'?<p className="text-xs text-muted-foreground">Euros hors taxes, deux décimales maximum. Vide signifie non renseigné.</p>:null}</div>)}
 <fieldset className="space-y-2" aria-describedby={id('error-stage')}><legend className="text-sm font-medium">Étape</legend>{draft.base?<div className="flex flex-wrap gap-2">{Object.entries(OPPORTUNITY_STAGE_LABELS).map(([value,label],index)=><Button key={value} id={index===0?id('stage'):undefined} type="button" className="min-h-11" variant={draft.values.stage===value?'default':'outline'} aria-pressed={draft.values.stage===value} onClick={()=>{if(draft.values.stage!==value)select('stage',value);}}>{label}</Button>)}</div>:<p className="text-sm">À qualifier</p>}{error('stage')}</fieldset>
 <fieldset className="space-y-2" disabled={loading} aria-busy={loading} aria-describedby={id('error-primary_contact_id')}><legend className="text-sm font-medium">Contact principal · facultatif</legend><p className="text-sm [overflow-wrap:anywhere]">Sélection : {draft.values.primary_contact_id?contactName||'Chargement du nom…':'Aucun contact'}</p><Button id={id('primary_contact_id')} type="button" className="min-h-11" variant={draft.values.primary_contact_id?'outline':'default'} aria-pressed={!draft.values.primary_contact_id} onClick={()=>select('primary_contact_id',null)}>Sans contact principal</Button>{loading?<Skeleton className="h-24 w-full"/>:contacts?.status==='success'?<><ul className="space-y-1">{contacts.contacts.map(contact=><li key={contact.id}><Button type="button" className="h-auto min-h-11 w-full justify-start whitespace-normal text-left" variant={draft.values.primary_contact_id===contact.id?'default':'outline'} aria-pressed={draft.values.primary_contact_id===contact.id} onClick={()=>{if(draft.values.primary_contact_id!==contact.id)select('primary_contact_id',contact.id);}}>{[contact.first_name,contact.last_name].filter(Boolean).join(' ')}</Button></li>)}</ul>{contacts.total>25?<div className="flex flex-wrap gap-2"><Button type="button" className="min-h-11" variant="outline" disabled={contactPage===1} onClick={()=>{setLoading(true);setContactPage(page=>page-1);}}>Contacts précédents</Button><Button type="button" className="min-h-11" variant="outline" disabled={contactPage*25>=contacts.total} onClick={()=>{setLoading(true);setContactPage(page=>page+1);}}>Contacts suivants</Button></div>:null}</>:<p role="alert">{contacts?.message??'Liste indisponible.'}</p>}{error('primary_contact_id')}</fieldset>
 {!loading&&contacts?.status!=='success'?<Button type="button" className="min-h-11" variant="outline" onClick={()=>setRetry(value=>value+1)}>Recharger les relations</Button>:null}
 {state.conflict?<section className="space-y-3" role="alert"><p>Certains champs ont changé ailleurs. Choisissez pour chacun.</p>{conflictFields.map(field=><fieldset key={field} className="space-y-2"><legend className="text-sm font-medium">{OPPORTUNITY_FIELD_LABELS[field]}</legend><p className="whitespace-pre-wrap text-xs [overflow-wrap:anywhere]">Valeur enregistrée : {conflictValue(field)}</p><div className="flex flex-wrap gap-2"><Button type="button" className="min-h-11" variant={choices[field]==='mine'?'default':'outline'} aria-pressed={choices[field]==='mine'} onClick={()=>setChoices(value=>({...value,[field]:'mine'}))}>Garder ma saisie · {OPPORTUNITY_FIELD_LABELS[field]}</Button><Button type="button" className="min-h-11" variant={choices[field]==='server'?'default':'outline'} aria-pressed={choices[field]==='server'} onClick={()=>setChoices(value=>({...value,[field]:'server'}))}>Garder la valeur enregistrée · {OPPORTUNITY_FIELD_LABELS[field]}</Button></div></fieldset>)}<Button type="button" className="min-h-11" disabled={conflictFields.some(field=>!choices[field])} onClick={()=>{store.resolve(target,choices);setChoices({});}}>Préparer les choix</Button></section>:null}
 {state.storageError?<p role="alert" className="text-sm text-destructive">Stockage indisponible. Gardez la fiche ouverte jusqu’à confirmation et nettoyage du brouillon.</p>:null}{state.message?<p role="status" data-opportunity-message className="text-sm">{state.message}</p>:null}
 <div className="flex flex-wrap gap-2 border-t pt-4" onPointerDownCapture={()=>{preventBlur.current=true;}}><Button type="button" className="min-h-11" disabled={state.busy||Boolean(state.conflict)} onClick={()=>save(false).catch(onCancelClose)}>{state.busy?'Enregistrement…':draft.pending?'Réessayer la confirmation':draft.base?'Enregistrer':'Ajouter'}</Button><Button type="button" className="min-h-11" onClick={requestClose}>Annuler</Button></div>
 </div><Dialog open={closing} onOpenChange={open=>{if(!open)cancel();}}><DialogContent ref={container} tabIndex={-1} onOpenAutoFocus={event=>{event.preventDefault();container.current?.focus();}} onCloseAutoFocus={event=>{if(focusInvalid())event.preventDefault();}}><DialogHeader><DialogTitle>Conserver votre saisie ?</DialogTitle><DialogDescription>Les changements ne sont pas tous confirmés.</DialogDescription></DialogHeader><DialogFooter><Button className="min-h-11" disabled={state.busy||Boolean(state.conflict)} onClick={()=>save(true).catch(cancel)}>Enregistrer</Button><Button className="min-h-11" variant="outline" disabled={state.busy} onClick={()=>{if(store.discard(target))onClose();else cancel();}}>Abandonner</Button><Button className="min-h-11" variant="ghost" onClick={cancel}>Continuer la saisie</Button></DialogFooter></DialogContent></Dialog></>;
}
