'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {useRouter} from 'next/navigation';
import {Plus,X,RefreshCw} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {OpportunitiesBoard} from './opportunities-board';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription,DialogFooter} from '@/components/ui/dialog';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Skeleton} from '@/components/ui/skeleton';
import {OpportunityEditor,type OpportunityEditorHandle} from './opportunity-editor';
import {createOpportunitiesCache,createOpportunityStore} from '@/lib/opportunities-cache';
import {fetchOpportunities,type OpportunityContext} from '@/lib/opportunities-transport';
import {opportunityDraftTargets,readOpportunityDraft} from '@/lib/opportunities-drafts';
import {type Opportunity,type OpportunityReadResult,type OpportunitiesPage} from '@/lib/validations/opportunities';
export function OpportunitiesShell({ownerId,initial,initialPage,initialPanel,context}:{ownerId:string;initial:OpportunitiesPage;initialPage:number;initialPanel:string|null;context:OpportunityContext}){
 const router=useRouter();const [cache]=useState(()=>createOpportunitiesCache(ownerId));const savedRef=useRef<(item:Opportunity,target:string)=>void>(()=>undefined);const [store]=useState(()=>createOpportunityStore(ownerId,(item,target)=>savedRef.current(item,target)));
 const [mounted,setMounted]=useState(false);const [cardGuard,setCardGuard]=useState<string|null>(null),[guardBusy,setGuardBusy]=useState(false);const guardedAction=useRef<(()=>void)|null>(null);
 const newTarget=context.contact_id?`new:contact:${context.contact_id}`:context.company_id?`new:company:${context.company_id}`:'new';
 const [list,setList]=useState(initial),[page,setPage]=useState(initialPage),[selected,setSelected]=useState(initialPanel),[target,setTarget]=useState(initialPanel==='new'?newTarget:initialPanel),[panel,setPanel]=useState<OpportunityReadResult|null>(null),[loading,setLoading]=useState(false),[drafts,setDrafts]=useState<string[]>([]),[panelError,setPanelError]=useState('');
 const selectedRef=useRef(selected),pageRef=useRef(page),allowed=useRef(true),listEpoch=useRef(0),panelEpoch=useRef(0),pending=useRef<{id:string|null;page:number;href?:string;target?:string}|null>(null),editor=useRef<OpportunityEditorHandle|null>(null),returnFocus=useRef<HTMLElement|null>(null),sheet=useRef<HTMLDivElement>(null),add=useRef<HTMLButtonElement>(null);
 const writeUrl=useCallback((id:string|null,nextPage=pageRef.current)=>{const url=new URL(window.location.href);if(id)url.searchParams.set('panel',id);else url.searchParams.delete('panel');if(nextPage>1)url.searchParams.set('page',String(nextPage));else url.searchParams.delete('page');window.history.replaceState(null,'',url);},[]);
 const denied=(status:string)=>{if(status==='unauthenticated'||status==='forbidden')window.dispatchEvent(new Event('crm-session-denied'));};
 const refreshList=useCallback(async(nextPage=pageRef.current)=>{if(!allowed.current)return;const stamp=++listEpoch.current;setLoading(true);const result=await fetchOpportunities(nextPage,context);if(!allowed.current||stamp!==listEpoch.current)return;denied(result.status);if(result.status==='success'){for(const item of result.opportunities){cache.put(item);store.refresh(item.id,item);}const last=Math.max(1,Math.ceil(result.total/25));if(nextPage>last){pageRef.current=last;setPage(last);writeUrl(selectedRef.current,last);await refreshList(last);return;}}setList(result);setLoading(false);},[cache,store,context.contact_id,context.company_id,writeUrl]);
 const refreshPanel=useCallback(async(id:string,targetId=id)=>{if(id==='new')return;const stamp=++panelEpoch.current;const result=await cache.load(id);if(!allowed.current||stamp!==panelEpoch.current||selectedRef.current!==id)return;denied(result.status);if(result.status==='success'){store.ensure(targetId,result.opportunity);store.refresh(targetId,result.opportunity);setPanelError('');setPanel(result);}else{setPanelError(result.message);setPanel(previous=>previous?.status==='success'?previous:result);}},[cache,store]);
 const open=useCallback((id:string,draftTarget?:string)=>{returnFocus.current=document.activeElement instanceof HTMLElement?document.activeElement:null;selectedRef.current=id;setSelected(id);editor.current=null;const nextTarget=draftTarget??(id==='new'?newTarget:id);setTarget(nextTarget);setPanelError('');if(id==='new'){store.ensure(nextTarget,null,context);setPanel(null);}else{const seed=cache.get(id);if(seed)store.ensure(nextTarget,seed);setPanel(seed?{status:'success',opportunity:seed}:null);refreshPanel(id,nextTarget).catch(()=>setPanelError('Fiche indisponible.'));}writeUrl(id);},[cache,store,newTarget,context.contact_id,context.company_id,refreshPanel,writeUrl]);
 const close=()=>{if(target&&store.busy(target))return;setSelected(null);selectedRef.current=null;setTarget(null);setPanel(null);panelEpoch.current++;editor.current=null;writeUrl(null);setDrafts(opportunityDraftTargets(ownerId));const next=pending.current;pending.current=null;if(next){if(next.href){router.push(next.href);return;}if(next.page!==pageRef.current){pageRef.current=next.page;setPage(next.page);refreshList(next.page).catch(()=>undefined);}if(next.id)open(next.id,next.target);else writeUrl(null,next.page);}};
 const request=(id:string|null,nextPage=pageRef.current,href?:string,draftTarget?:string)=>{if(id&&id===selectedRef.current&&nextPage===pageRef.current&&!href)return;const dirty=list.status==='success'?list.opportunities.find(item=>item.id!==id&&item.id!==selectedRef.current&&(store.dirty(item.id)||store.busy(item.id))):undefined;if(dirty){guardedAction.current=()=>request(id,nextPage,href,draftTarget);setCardGuard(dirty.id);return;}if(selectedRef.current){pending.current={id,page:nextPage,href,target:draftTarget};if(editor.current)editor.current.requestClose();else close();}else if(href)router.push(href);else if(id)open(id,draftTarget);else{pageRef.current=nextPage;setPage(nextPage);writeUrl(null,nextPage);refreshList(nextPage).catch(()=>undefined);}};
 savedRef.current=(item,targetId)=>{if(!allowed.current)return;cache.put(item);if((target===targetId&&selectedRef.current)||selectedRef.current===item.id){selectedRef.current=item.id;setSelected(item.id);setPanel({status:'success',opportunity:cache.get(item.id)!});writeUrl(item.id);}refreshList().catch(()=>undefined);};
 useEffect(()=>{allowed.current=true;setMounted(true);setDrafts(opportunityDraftTargets(ownerId));if(initial.status==='success')initial.opportunities.forEach(item=>cache.put(item));if(initialPanel==='new')store.ensure(newTarget,null,context);else if(initialPanel)refreshPanel(initialPanel).catch(()=>undefined);refreshList().catch(()=>undefined);
  const refresh=()=>{if(!allowed.current)return;refreshList().catch(()=>undefined);if(selectedRef.current&&selectedRef.current!=='new')refreshPanel(selectedRef.current).catch(()=>undefined);};const expire=()=>{allowed.current=false;listEpoch.current++;panelEpoch.current++;cache.clear();store.expire();setSelected(null);selectedRef.current=null;setPanel(null);setList({status:'unauthenticated',message:'Session terminée.'});};for(const event of ['focus','online','crm-data-changed','crm-session-ready'])window.addEventListener(event,refresh);window.addEventListener('crm-session-expired',expire);return()=>{allowed.current=false;listEpoch.current++;panelEpoch.current++;for(const event of ['focus','online','crm-data-changed','crm-session-ready'])window.removeEventListener(event,refresh);window.removeEventListener('crm-session-expired',expire);};},[cache,store,refreshList,refreshPanel]);
 useEffect(()=>{const pop=()=>{const url=new URL(window.location.href);const candidate=url.searchParams.get('panel');const id=candidate&&(candidate==='new'||/^[0-9a-f-]{36}$/i.test(candidate))?candidate:null;const n=Number(url.searchParams.get('page')??1);const p=Number.isInteger(n)&&n>0?n:1;if(id!==selectedRef.current||p!==pageRef.current){writeUrl(selectedRef.current);request(id,p);}};const navigate=(event:MouseEvent)=>{if(event.defaultPrevented||event.metaKey||event.ctrlKey||event.altKey||event.shiftKey)return;const anchor=(event.target as HTMLElement).closest('a[href]');if(!(anchor instanceof HTMLAnchorElement)||anchor.origin!==location.origin||anchor.pathname===location.pathname)return;event.preventDefault();event.stopPropagation();request(null,pageRef.current,anchor.href);};window.addEventListener('popstate',pop);document.addEventListener('click',navigate,true);return()=>{window.removeEventListener('popstate',pop);document.removeEventListener('click',navigate,true);};});
 useEffect(()=>{if(!selected||list.status!=='success')return;const index=list.opportunities.findIndex(item=>item.id===selected);if(index<0)return;for(const item of list.opportunities.slice(Math.max(0,index-3),index+4))cache.load(item.id).catch(()=>undefined);},[selected,list,cache]);
 useEffect(()=>{const unload=(event:BeforeUnloadEvent)=>{if(list.status==='success'&&list.opportunities.some(item=>store.dirty(item.id)||store.busy(item.id)))event.preventDefault();};window.addEventListener('beforeunload',unload);return()=>window.removeEventListener('beforeunload',unload);},[list,store]);
 const prefetch=(id:string)=>cache.load(id).catch(()=>undefined);
 if(selected==='new'&&target)store.ensure(target,null,context);
 return <><div className={selected?'min-w-0 lg:mr-[460px]':'min-w-0'}><header data-opportunities-ready={mounted} className="mb-6 flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-[length:var(--text-heading)] font-semibold tracking-tight">Pipeline</h1><p className="mt-2 text-sm text-muted-foreground">Vos opportunités et leur contexte.</p></div><Button ref={add} className="min-h-11" onClick={()=>request('new')}><Plus/>Nouvelle opportunité</Button></header>
 {context.contact_id||context.company_id?<p className="mb-4 text-sm">Opportunités liées au {context.contact_id?'contact':'contexte société'}. <Button variant="link" className="min-h-11" onClick={()=>request(null,pageRef.current,'/pipeline')}>Toutes les opportunités</Button></p>:null}
 {drafts.length?<div className="mb-4 flex flex-wrap gap-2">{drafts.map(key=>{const draft=readOpportunityDraft(ownerId,key);return <Button key={key} variant="outline" className="h-auto min-h-11 whitespace-normal" onClick={()=>request(draft?.base?.id??'new',pageRef.current,undefined,key)}>Reprendre : {draft?.values.title||'Nouvelle opportunité'}</Button>;})}</div>:null}
 <div className="mb-3 flex items-center justify-between"><p className="text-xs" role="status">{list.status==='success'?`${list.total} opportunité${list.total>1?'s':''}`:'Liste indisponible'}{loading?' · Actualisation…':''}</p><Button variant="ghost" className="min-h-11" disabled={loading} onClick={()=>refreshList().catch(()=>undefined)}><RefreshCw/>Actualiser</Button></div>
 {list.status!=='success'?<div role="alert" className="space-y-3 rounded-md border p-5"><p>{list.message}</p><Button className="min-h-11" onClick={()=>refreshList().catch(()=>undefined)}>Réessayer</Button></div>:<><OpportunitiesBoard items={list.opportunities} store={store} selected={selected} mounted={mounted} onOpen={id=>request(id)} onPrefetch={prefetch}/><p className="mt-2 text-xs text-muted-foreground">25 opportunités par page, toutes étapes confondues. Les compteurs des colonnes concernent cette page. Pour changer d’étape, ouvrez une fiche.</p><div className="mt-4 flex flex-wrap items-center justify-between gap-2"><p className="text-xs">Page {page} / {Math.max(1,Math.ceil(list.total/25))} · 25 par page</p><div className="flex gap-2"><Button className="min-h-11" variant="outline" disabled={loading||page===1} onClick={()=>request(null,page-1)}>Précédent</Button><Button className="min-h-11" variant="outline" disabled={loading||page*25>=list.total} onClick={()=>request(null,page+1)}>Suivant</Button></div></div></>}
 </div><Dialog open={Boolean(cardGuard)} onOpenChange={value=>{if(!value){setCardGuard(null);guardedAction.current=null;}}}><DialogContent><DialogHeader><DialogTitle>Conserver votre saisie ?</DialogTitle><DialogDescription>Cette carte contient des changements non confirmés.</DialogDescription></DialogHeader><DialogFooter><Button disabled={guardBusy} onClick={async()=>{if(!cardGuard)return;setGuardBusy(true);const ok=await store.save(cardGuard);setGuardBusy(false);setCardGuard(null);if(ok&&!store.dirty(cardGuard)){const action=guardedAction.current;guardedAction.current=null;action?.();}else open(cardGuard);}}>Enregistrer</Button><Button variant="outline" disabled={guardBusy||Boolean(cardGuard&&(store.busy(cardGuard)||store.get(cardGuard).draft.pending))} onClick={()=>{if(cardGuard&&store.discard(cardGuard)){setCardGuard(null);const action=guardedAction.current;guardedAction.current=null;action?.();}}}>Abandonner</Button><Button variant="ghost" onClick={()=>{setCardGuard(null);guardedAction.current=null;}}>Continuer la saisie</Button></DialogFooter></DialogContent></Dialog><Sheet modal={false} open={Boolean(selected)} onOpenChange={value=>{if(!value){if(editor.current)editor.current.requestClose();else close();}}}><SheetContent ref={sheet} onInteractOutside={event=>event.preventDefault()} showCloseButton={false} className="w-full gap-5 sm:max-w-[460px]" tabIndex={-1} onOpenAutoFocus={event=>{event.preventDefault();sheet.current?.focus();}} onCloseAutoFocus={event=>{event.preventDefault();if(returnFocus.current?.isConnected)returnFocus.current.focus();else add.current?.focus();}}><SheetHeader className="border-b px-5 py-5 pr-16"><SheetTitle>{selected==='new'?'Nouvelle opportunité':'Fiche opportunité'}</SheetTitle><SheetDescription>Titre, montant hors taxes, Notes et contact principal.</SheetDescription></SheetHeader><Button aria-label="Fermer l’opportunité" variant="ghost" size="icon" className="absolute right-3 top-3 min-h-11 min-w-11" onClick={()=>{if(editor.current)editor.current.requestClose();else close();}}><X/></Button><div className="min-h-0 flex-1 overflow-y-auto">{panelError?<p role="alert" className="px-5 text-sm text-destructive">{panelError}</p>:null}{target&&mounted&&(selected==='new'||panel?.status==='success')?<OpportunityEditor key={target} store={store} target={target} handle={editor} onClose={close} onCancelClose={()=>{pending.current=null;}}/>:panel&&panel.status!=='success'?<div role="alert" className="space-y-3 px-5"><p>{panel.message}</p><Button className="min-h-11" onClick={()=>{if(selected)refreshPanel(selected).catch(()=>undefined);}}>Réessayer la fiche</Button></div>:<div className="space-y-5 px-5" aria-label="Chargement de l’opportunité" role="status">{Array.from({length:4},(_,i)=><Skeleton key={i} className="h-20 w-full"/>)}</div>}</div></SheetContent></Sheet>
 </>;
}
