"use client";
import { useEffect,useRef,useState } from "react";
import { z } from "zod";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import { fetchCompanies, fetchCompany } from "@/lib/companies-transport";
import { contactCompanySchema,contactCompanyCommandSchema,contactCompanyReadSchema,contactCompanyResultSchema,type ContactCompany,type ContactCompanyCommand,type CompaniesPage } from "@/lib/validations/companies";
const draftSchema=z.object({base:contactCompanySchema,value:z.uuid().nullable(),value_name:z.string().optional(),generation:z.number().int().nonnegative(),pending:z.object({command:contactCompanyCommandSchema,generation:z.number().int().nonnegative(),value:z.uuid().nullable()}).nullable()});
type Draft=z.infer<typeof draftSchema>;
export type CompanyEditorHandle={dirty:()=>boolean;hasPending:()=>boolean;save:()=>Promise<boolean>;discard:()=>void};
const key=(owner:string,id:string)=>`crm:contact-company:draft:${owner}:${id}`;
export function relationDraftTargets(owner:string){try{return Object.keys(sessionStorage).filter(k=>k.startsWith(`crm:contact-company:draft:${owner}:`)).map(k=>k.slice(`crm:contact-company:draft:${owner}:`.length)).filter(id=>z.uuid().safeParse(id).success);}catch{return [];}}
export function ContactCompanyEditor({ownerId,contactId,handle}:{ownerId:string;contactId:string;handle:React.RefObject<CompanyEditorHandle|null>}){
 const [draft,setDraft]=useState<Draft|null>(null),ref=useRef<Draft|null>(null);
 const [recover,setRecover]=useState<Draft|null>(null),recoverRef=useRef<Draft|null>(null);
 const [list,setList]=useState<CompaniesPage|null>(null),[page,setPage]=useState(1),[listLoading,setListLoading]=useState(false),[message,setMessage]=useState(""),[saving,setSaving]=useState(false),[conflict,setConflict]=useState<ContactCompany|null>(null);
 const [relationLoading,setRelationLoading]=useState(true),[relationError,setRelationError]=useState(""),[listRetry,setListRetry]=useState(0);
 const [selectedName,setSelectedName]=useState<{id:string;name:string}|null>(null),[selectedError,setSelectedError]=useState(""),[selectedRetry,setSelectedRetry]=useState(0);
 const active=useRef(true),flight=useRef(false),readEpoch=useRef(0),listEpoch=useRef(0);
 const dirty=(d:Draft|null)=>Boolean(d&&(d.pending||d.value!==(d.base.company?.id??null)));
 const store=(d:Draft)=>{ref.current=d;setDraft(d);try{if(dirty(d))sessionStorage.setItem(key(ownerId,contactId),JSON.stringify(d));else sessionStorage.removeItem(key(ownerId,contactId));}catch{setMessage("Stockage indisponible. Gardez cette fiche ouverte jusqu’à confirmation.");}};
 const denied=(status:string)=>{if(status==="unauthenticated"||status==="forbidden")window.dispatchEvent(new Event("crm-session-denied"));};
 async function refresh(){
  const epoch=++readEpoch.current;setRelationLoading(true);setRelationError("");
  try{
   const response=await fetch(`/api/contacts/company?id=${contactId}`,{cache:"no-store",credentials:"same-origin",signal:AbortSignal.timeout(15000)});
   const result=contactCompanyReadSchema.parse(await response.json());if(!active.current||epoch!==readEpoch.current)return;
   denied(result.status);
   if(result.status==="success"){
    if(!flight.current&&!dirty(ref.current)&&!recoverRef.current&&result.relation.version>=(ref.current?.base.version??0))store({base:result.relation,value:result.relation.company?.id??null,generation:0,pending:null});
   }else setRelationError(result.message);
  }catch{if(active.current&&epoch===readEpoch.current)setRelationError("Société indisponible. Votre sélection est conservée.");}
  finally{if(active.current&&epoch===readEpoch.current)setRelationLoading(false);}
 }

 useEffect(()=>{active.current=true;try{const parsed=draftSchema.safeParse(JSON.parse(sessionStorage.getItem(key(ownerId,contactId))??"null"));if(parsed.success&&parsed.data.base.contact_id===contactId){setRecover(parsed.data);recoverRef.current=parsed.data;}}catch{/* No usable stored draft. */}refresh().catch(()=>undefined);const update=()=>refresh().catch(()=>undefined);const before=(e:BeforeUnloadEvent)=>{if(dirty(ref.current)||recoverRef.current)e.preventDefault();};window.addEventListener("focus",update);window.addEventListener("online",update);window.addEventListener("crm-data-changed",update);window.addEventListener("beforeunload",before);return()=>{active.current=false;readEpoch.current++;listEpoch.current++;window.removeEventListener("focus",update);window.removeEventListener("online",update);window.removeEventListener("crm-data-changed",update);window.removeEventListener("beforeunload",before);};},[contactId,ownerId]);
 useEffect(()=>{const load=()=>{const epoch=++listEpoch.current;setListLoading(true);fetchCompanies(page).then(result=>{if(!active.current||epoch!==listEpoch.current)return;setList(result);setListLoading(false);denied(result.status);}).catch(()=>{if(active.current){setListLoading(false);setList({status:"unavailable",message:"Liste des sociétés indisponible."});}});};load();window.addEventListener("focus",load);window.addEventListener("online",load);window.addEventListener("crm-data-changed",load);return()=>{listEpoch.current++;window.removeEventListener("focus",load);window.removeEventListener("online",load);window.removeEventListener("crm-data-changed",load);};},[page,listRetry]);
 const selectedDraft=recover??draft;
 const selectedId=selectedDraft?.value??null;
 useEffect(()=>{let current=true;let nameEpoch=0;setSelectedError("");if(!selectedId){setSelectedName(null);return;}
  const load=()=>{const epoch=++nameEpoch;return fetchCompany(selectedId).then(result=>{if(!current||epoch!==nameEpoch)return;denied(result.status);if(result.status==="success"){setSelectedName({id:selectedId,name:result.company.name});setSelectedError("");}else setSelectedError(result.message);}).catch(()=>{if(current&&epoch===nameEpoch)setSelectedError("Nom de la sélection indisponible.");});};
  load().catch(()=>undefined);const refreshName=()=>load().catch(()=>undefined);window.addEventListener("crm-data-changed",refreshName);window.addEventListener("focus",refreshName);window.addEventListener("online",refreshName);
  return()=>{current=false;window.removeEventListener("crm-data-changed",refreshName);window.removeEventListener("focus",refreshName);window.removeEventListener("online",refreshName);};
 },[selectedId,selectedRetry]);
 const selectedLabel=selectedId?(selectedName?.id===selectedId?selectedName.name:selectedDraft?.value_name??(selectedDraft?.base.company?.id===selectedId?selectedDraft.base.company.name:null)):"Aucune société";
 const discard=()=>{try{sessionStorage.removeItem(key(ownerId,contactId));}catch{/* Explicit abandon only. */}recoverRef.current=null;setRecover(null);setConflict(null);if(ref.current)store({...ref.current,value:ref.current.base.company?.id??null,value_name:ref.current.base.company?.name,pending:null});};
 const save=async()=>{if(flight.current||recoverRef.current||conflict||!ref.current)return false;if(!dirty(ref.current))return true;const current=ref.current;const pending=current.pending??{command:{command_id:crypto.randomUUID(),contact_id:contactId,company_id:current.value,base_version:current.base.version} satisfies ContactCompanyCommand,generation:current.generation,value:current.value};readEpoch.current++;setRelationLoading(false);store({...current,pending});flight.current=true;setSaving(true);setMessage("");try{const response=await fetch("/api/contacts/company",{method:"POST",credentials:"same-origin",headers:{"Content-Type":"application/json"},body:JSON.stringify(pending.command),signal:AbortSignal.timeout(15000)});const result=contactCompanyResultSchema.parse(await response.json());if(!active.current)return false;denied(result.status);if(result.status==="success"){readEpoch.current++;const latest=ref.current!;const next={...latest,base:result.relation,pending:null,value:latest.generation===pending.generation?result.relation.company?.id??null:latest.value};store(next);setMessage(dirty(next)?"Société enregistrée. Votre nouvelle sélection reste à enregistrer.":"Société enregistrée.");window.dispatchEvent(new Event("crm-data-changed"));return !dirty(next);}if(result.status!=="unavailable")store({...ref.current!,pending:null});if(result.status==="conflict")setConflict(result.relation);setMessage(result.message);return false;}catch{if(active.current)setMessage("Confirmation indisponible. Réessayez la même sélection.");return false;}finally{flight.current=false;if(active.current)setSaving(false);}};
 handle.current={dirty:()=>dirty(ref.current)||Boolean(recoverRef.current),hasPending:()=>Boolean(ref.current?.pending),save,discard};
 const select=(value:string|null,name?:string)=>{if(!ref.current)return;store({...ref.current,value,value_name:name,generation:ref.current.generation+1});setMessage("");};
 return <section aria-label="Société du contact" className="space-y-3 border-t pt-5"><h2 className="text-sm font-medium">Société <span className="font-normal text-muted-foreground">Facultatif</span></h2>
 {recover?<div className="space-y-2" role="status"><p className="text-sm">Une sélection de société est à reprendre.</p><Button type="button" className="min-h-11" onClick={()=>{store(recover);recoverRef.current=null;setRecover(null);}}>Reprendre la sélection</Button><Button type="button" variant="outline" className="min-h-11" onClick={()=>{discard();refresh().catch(()=>undefined);}}>Abandonner la sélection</Button></div>:null}
 {selectedDraft?<p className="text-sm [overflow-wrap:anywhere]" aria-live="polite">Sélection à enregistrer : {selectedLabel??(selectedError?"Nom indisponible":"Chargement du nom…")}</p>:null}
 {selectedError?<div role="alert"><p className="text-sm">{selectedError}</p><Button type="button" variant="outline" className="min-h-11" onClick={()=>setSelectedRetry(n=>n+1)}>Recharger le nom sélectionné</Button></div>:null}
 {relationError?<div role="alert"><p className="text-sm">{relationError}</p><Button type="button" variant="outline" className="min-h-11" disabled={relationLoading} onClick={()=>refresh().catch(()=>undefined)}>Recharger la société</Button></div>:null}
 {draft?<><p className="text-sm [overflow-wrap:anywhere]">Société enregistrée : {draft.base.company?<a className="inline-flex min-h-11 max-w-full items-center whitespace-normal [overflow-wrap:anywhere] underline" href={`/societes?panel=${draft.base.company.id}`}><span className="min-w-0 [overflow-wrap:anywhere]">{draft.base.company.name}</span></a>:"Aucune société"}</p><div className="space-y-2" aria-busy={listLoading}><Button type="button" variant={draft.value===null?"default":"outline"} aria-pressed={draft.value===null} className="min-h-11" disabled={Boolean(recover)} onClick={()=>select(null)}>Aucune société</Button>{list?.status==="success"?<><p className="text-xs text-muted-foreground">{list.total} sociétés · page {page} sur {Math.max(1,Math.ceil(list.total/25))}</p><ul className="space-y-1">{list.companies.map(company=><li key={company.id}><Button type="button" variant={draft.value===company.id?"default":"outline"} aria-pressed={draft.value===company.id} disabled={Boolean(recover)||listLoading} className="h-auto min-h-11 w-full justify-start whitespace-normal text-left" onClick={()=>select(company.id,company.name)}><span className="min-w-0 [overflow-wrap:anywhere]">{company.name}</span></Button></li>)}</ul>{list.total===0?<p className="text-sm">Aucune société disponible.</p>:null}<div className="flex flex-wrap gap-2"><Button type="button" variant="outline" className="min-h-11" disabled={page===1||listLoading} onClick={()=>setPage(p=>p-1)}>Sociétés précédentes</Button><Button type="button" variant="outline" className="min-h-11" disabled={page*25>=list.total||listLoading} onClick={()=>setPage(p=>p+1)}>Sociétés suivantes</Button></div></>:list?<div role="alert"><p>{list.message}</p><Button type="button" variant="outline" className="min-h-11" disabled={listLoading} onClick={()=>setListRetry(n=>n+1)}>Recharger les sociétés</Button></div>:<Skeleton className="h-11 w-full"/>}</div></>:recover?null:relationLoading?<Skeleton className="h-11 w-full"/>:null}
 {conflict?<div className="space-y-2" role="alert"><p className="text-sm [overflow-wrap:anywhere]">Société enregistrée ailleurs : {conflict.company?.name??"Aucune"}</p><Button type="button" className="min-h-11" onClick={()=>{store({...ref.current!,base:conflict,pending:null});setConflict(null);setMessage("Choix préparé. Enregistrez pour confirmer.");}}>Garder ma sélection</Button><Button type="button" variant="outline" className="min-h-11" onClick={()=>{store({...ref.current!,base:conflict,value:conflict.company?.id??null,value_name:conflict.company?.name,pending:null});setConflict(null);}}>Utiliser la société enregistrée</Button></div>:null}
 {saving?<p role="status" className="text-sm">Enregistrement de la société…</p>:null}{message?<p role="status" className="text-sm">{message}</p>:null}<p className="text-xs text-muted-foreground">Utilisez Enregistrer pour confirmer la sélection.</p></section>;
}
